### ISSUE TITLE
Game Tick Delay Bug

### ISSUE THREAD

**Issue by Xevion** [LucaFeggi/PacMan_SDL#8]
Hi,

I believe I have discovered a bug in your game code.

In the game loop, we have this section of code:

```cpp
if(mGame.Process(GameTimer, mover, StartTicks)){
    mGame.Draw();
    SDL_RenderPresent(renderer);
}
```

Following this, we calculate the elapsed time in milliseconds for this loop:

```cpp
uint64_t IterationEnd = SDL_GetPerformanceCounter();
float elapsedMS = (IterationEnd - IterationStart) / ((float)SDL_GetPerformanceFrequency() * 1000.0f);
SDL_Delay(floor(11.111f - elapsedMS));
```

You can find the offending lines of code [here](https://github.com/LucaFeggi/PacMan_SDL/blob/e2a7e7f5b32e6f002ba91c679ad878c978ca4ea1/main.cpp#L68C55-L70
).

Now, here's where things get interesting. We are converting seconds to milliseconds by multiplying by 1000, which turns 0.05 seconds into 0.00005 milliseconds instead of the intended 50 milliseconds. Consequently, the delay always remains at a strict 11 milliseconds, regardless of how long the tick actually took. This delay setup would only have a meaningful impact on timing if the tick took a full second or even longer.

In a standard scenario, a dynamic delay of 11 milliseconds would suggest that the developer is aiming for approximately 90 frames per second (1000 / 11.11 ≈ 90.009).

I added some debug `printf` calls and calculated the elapsed time properly, and here's what I got:
![image](https://github.com/LucaFeggi/PacMan_SDL/assets/44609630/0fa4df18-3118-4d58-800c-d7335d4fbce8)
- The first line is the elapsed time the original code calculated (the bool is whether or not it called `draw()`).
- The second line is the actual integer delay completed with `SDL_Delay(...)`.
- The third line is the actual amount of time elapsed during the tick/draw process. It's what the first line SHOULD have calculated.

The proper elapsed time calculation would look something like the following:

```cpp
double seconds_elapsed = (IterationEnd - IterationStart) / (double)SDL_GetPerformanceFrequency();
double ms_elapsed = seconds_elapsed * 1000.0;
```

However, there's another factor to consider. The tick and draw process itself takes about 5 milliseconds. So, on average, we're spending 16 milliseconds between draws. If you're familiar with the concept of 60 FPS and game loops, you'll recognize that 60 FPS corresponds to approximately 16.67 milliseconds.

This means that even though it might appear as though the game is targeting 90 FPS, it's actually performing more like a 60 FPS game due to these timing quirks.

Thanks for your attention!

**Comment by LucaFeggi** [comment]
Thanks for noticing that!
Now, I should have fix it. You can see the update in the main.cpp file of the project.
